api_endpoint:
  default: "https://api.example.com/endpoint"
  client: true
api_key:
  default: ""
  client: true
  description: "Discourse API key for error reporting via topic creation"
category_id:
  default: 0
  description: "Category ID for topic creation for error reporting"
  client: true
blocks:
  default: >-
    []
  json_schema: >-
    {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "html": {
            "type": "string",
            "description": "Custom HTML content for this block"
          },
          "tags": {
            "type": "array",
            "format": "table",
            "uniqueItems": true,
            "description": "Comma-separated list of tags for this block",
            "items": {
              "type": "string"
            }
          },
          "placementID": {
            "type": "string",
            "description": "Placement ID for this block"
          },
          "campaignID": {
            "type": "string",
            "description": "Campaign ID for this block"
          }
        }
      }
    }