api_endpoint:
  default: "https://api.example.com/endpoint"
  client: true
error_notification_emails:
  default: ""
  client: false
  description: "Please enter a comma-separated list of email addresses to notify on API errors."
blocks:
  default: >-
    []
  json_schema: >-
    {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "html": {
            "type": "string",
            "description": "Custom HTML content for this block"
          },
          "tags": {
            "type": "array",
            "format": "table",
            "uniqueItems": true,
            "description": "Comma-separated list of tags for this block",
            "items": {
              "type": "string"
            }
          },
          "placementID": {
            "type": "string",
            "description": "Placement ID for this block"
          },
          "campaignID": {
            "type": "string",
            "description": "Campaign ID for this block"
          }
        }
      }
    }